[font]
size = 16.0

[font.bold]
family = "Caskaydia Cove Nerd Font"
style = "Bold"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "Caskaydia Cove Nerd Font"
style = "regular"

[window]
opacity = 0.95
